#!/bin/bash
# Build .app bundle
set -e
cd "$(dirname "$0")"

# --- load .env and bake Last.fm creds into _credentials.py ---
if [ ! -f ".env" ]; then
    echo "✗ .env not found — copy .env.example → .env and fill in Last.fm keys"
    echo "  register at: https://www.last.fm/api/account/create"
    exit 1
fi

# shellcheck disable=SC1091
set -a
source .env
set +a

if [ -z "${LASTFM_API_KEY:-}" ] || [ -z "${LASTFM_API_SECRET:-}" ]; then
    echo "✗ .env is missing LASTFM_API_KEY or LASTFM_API_SECRET"
    exit 1
fi

echo "→ writing _credentials.py (bundled into .app)"
cat > _credentials.py <<PYEOF
# Auto-generated by build.sh from .env — DO NOT commit
LASTFM_API_KEY = "${LASTFM_API_KEY}"
LASTFM_API_SECRET = "${LASTFM_API_SECRET}"
PYEOF

echo "→ cleaning old builds"
rm -rf build dist

echo "→ installing deps"
pip3 install -q -r requirements.txt

echo "→ building .app (release)"
python3 setup.py py2app

echo
echo "✓ done → dist/Apple Music Scrobbler.app"
echo "  open it with:  open 'dist/Apple Music Scrobbler.app'"
