#!/usr/bin/env python3
"""Apple Music Scrobbler — local server with tracking, Last.fm, webhook, artwork."""
__version__ = "1.0.0"

import http.server
import socketserver
import subprocess
import json
import sqlite3
import threading
import time
import hashlib
import urllib.parse
import urllib.request
import urllib.error
import os
import io
import csv
import re
from pathlib import Path

BASE_DIR = Path(__file__).parent.resolve()
# Static web assets (html / js) — override via env var when bundled as .app
WEB_DIR = Path(os.environ.get("AMS_WEB_DIR") or (BASE_DIR / "web"))
# Writable data dir — override via env var (e.g. when bundled as .app)
DATA_DIR = Path(os.environ.get("AMS_DATA_DIR") or BASE_DIR)
DATA_DIR.mkdir(parents=True, exist_ok=True)

# ============================================================
# Bundled Last.fm credentials
# ------------------------------------------------------------
# Release .app ships with LASTFM_API_KEY/SECRET baked in so end users
# don't need to register their own. Priority:
#   1. _credentials.py  (generated by build.sh from .env, bundled by py2app)
#   2. .env             (dev mode, sits next to server.py — gitignored)
# End users get Last.fm connection via OAuth-style token flow; they
# never see API keys. Devs override by editing .env or settings.json.
# ============================================================
def _load_bundled_credentials():
    try:
        import _credentials  # type: ignore
        key = (getattr(_credentials, "LASTFM_API_KEY", "") or "").strip()
        sec = (getattr(_credentials, "LASTFM_API_SECRET", "") or "").strip()
        if key or sec:
            return key, sec
    except Exception:
        pass
    env_path = BASE_DIR / ".env"
    if env_path.exists():
        try:
            parsed = {}
            for line in env_path.read_text().splitlines():
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                parsed[k.strip()] = v.strip().strip('"').strip("'")
            return parsed.get("LASTFM_API_KEY", "").strip(), parsed.get("LASTFM_API_SECRET", "").strip()
        except Exception:
            pass
    return "", ""

BUNDLED_LASTFM_API_KEY, BUNDLED_LASTFM_API_SECRET = _load_bundled_credentials()
HAS_BUNDLED_LASTFM = bool(BUNDLED_LASTFM_API_KEY and BUNDLED_LASTFM_API_SECRET)

DB_PATH = DATA_DIR / "history.db"
SETTINGS_PATH = DATA_DIR / "settings.json"
NOW_PLAYING_PATH = DATA_DIR / "now_playing.json"
EDIT_HISTORY_PATH = DATA_DIR / "edit_history.json"
PORT = 8765

# snapshot ปัจจุบันใน memory — เสิร์ฟจาก /api/nowplaying (เลี่ยง race กับการเขียนไฟล์)
CURRENT_NOW_PLAYING = {"data": {"playing": False}}

# ให้ Handler เข้าถึง tracker instance ได้ (ใช้ตอน reload artwork)
TRACKER_REF = {"t": None}

DEFAULT_SETTINGS = {
    "language": "th",
    "lastfm": {
        "api_key": "",
        "api_secret": "",
        "session_key": "",
        "username": "",
        "enabled": False,
        "pending_token": ""
    },
    "webhook": {
        "urls": [],
        "enabled": False,
        "heartbeat_seconds": 0
    },
    "scrobble": {
        "percent": 50,
        "min_seconds": 30
    },
    "notifications": {
        "enabled": True,
        "on_play": True,
        "on_scrobble": False
    },
    "menubar": {
        "show_icon": True,
        "show_track": True,
        "show_artist": False,
        "show_state": True,
        "max_length": 28
    }
}

CONTROL_SCRIPTS = {
    "playpause": 'tell application "Music" to playpause',
    "next":      'tell application "Music" to next track',
    "prev":      'tell application "Music" to previous track',
}

# ใช้ ASCII unit separator (0x1F) แทน `|` เพื่อเลี่ยง delimiter ชนกับชื่อเพลงที่มี `|`
_SEP = "|"
FETCH_STATE_SCRIPT = '''
set SEP to "|" -- เปลี่ยนเป็น Pipe เพื่อความชัวร์ในเรื่อง Encoding
tell application "Music"
    if it is running then
        set playerState to player state as string
        if playerState is "stopped" then
            return "stopped" & SEP & "0" & SEP & "0" & SEP & "" & SEP & "" & SEP & ""
        end if
        set pos to 0
        set dur to 0
        set nm to ""
        set ar to ""
        set al to ""
        
        try
            set pos to player position
        end try
        
        try
            set t to current track
            try
                set nm to name of t
            end try
            try
                set ar to artist of t
            end try
            try
                set al to album of t
            end try
            try
                set dur to duration of t
            end try
            
            -- Fallback for stream title if name is empty (for Radio stations)
            if nm is "" or nm is missing value then
                try
                    set nm to current stream title
                end try
            end if
        end try
        
        return playerState & SEP & pos & SEP & dur & SEP & nm & SEP & ar & SEP & al
    else
        return "stopped" & SEP & "0" & SEP & "0" & SEP & "" & SEP & "" & SEP & ""
    end if
end tell
'''

# ============================================================
# Settings
# ============================================================
_settings_lock = threading.Lock()

def _deep_merge(base, override):
    out = dict(base)
    for k, v in override.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out

def _apply_bundled_lastfm(settings):
    """Overlay bundled LASTFM creds when user hasn't provided their own."""
    if not HAS_BUNDLED_LASTFM:
        return settings
    lf = settings.setdefault("lastfm", {})
    if not lf.get("api_key"):
        lf["api_key"] = BUNDLED_LASTFM_API_KEY
    if not lf.get("api_secret"):
        lf["api_secret"] = BUNDLED_LASTFM_API_SECRET
    return settings

def load_settings():
    with _settings_lock:
        if not SETTINGS_PATH.exists():
            SETTINGS_PATH.write_text(json.dumps(DEFAULT_SETTINGS, indent=2))
            return _apply_bundled_lastfm(json.loads(json.dumps(DEFAULT_SETTINGS)))
        try:
            data = json.loads(SETTINGS_PATH.read_text())
            merged = _deep_merge(DEFAULT_SETTINGS, data)
            # Migration: convert single url to urls list
            wh = merged.get("webhook", {})
            if "url" in wh and not wh.get("urls"):
                old_url = wh.pop("url")
                if old_url:
                    wh["urls"] = [old_url]
            return _apply_bundled_lastfm(merged)
        except Exception:
            return _apply_bundled_lastfm(json.loads(json.dumps(DEFAULT_SETTINGS)))

def save_settings(updates):
    with _settings_lock:
        current = load_settings.__wrapped__() if hasattr(load_settings, "__wrapped__") else None
        if SETTINGS_PATH.exists():
            try:
                current = json.loads(SETTINGS_PATH.read_text())
            except Exception:
                current = {}
        else:
            current = {}
        merged = _deep_merge(_deep_merge(DEFAULT_SETTINGS, current), updates)
        SETTINGS_PATH.write_text(json.dumps(merged, indent=2))
        return merged

def public_settings(s=None):
    """Hide secrets when returning settings to the UI."""
    s = s or load_settings()
    lf = s["lastfm"]
    return {
        "lastfm": {
            # When creds come from the bundle, don't leak the key to the UI —
            # just tell the UI it's bundled so the "API keys" section can hide.
            "api_key": "" if HAS_BUNDLED_LASTFM else lf.get("api_key", ""),
            "api_secret_set": bool(lf.get("api_secret")),
            "api_bundled": HAS_BUNDLED_LASTFM,
            "connected": bool(lf.get("session_key")),
            "username": lf.get("username", ""),
            "enabled": lf.get("enabled", False),
            "has_pending_token": bool(lf.get("pending_token"))
        },
        "webhook": s["webhook"],
        "scrobble": s["scrobble"],
        "notifications": s.get("notifications", DEFAULT_SETTINGS["notifications"]),
        "menubar": s.get("menubar", DEFAULT_SETTINGS["menubar"]),
        "language": s.get("language", DEFAULT_SETTINGS["language"]),
        "version": __version__,
    }

# ============================================================
# Edit history (ชื่อเพลง/ศิลปิน/อัลบั้ม ที่แก้ไว้ล่วงหน้า — format ตรงกับ Music-Scrobbler)
# ============================================================
_edit_lock = threading.Lock()
_edit_cache = {}
_edit_loaded = False

def edits_load():
    global _edit_cache, _edit_loaded
    with _edit_lock:
        if _edit_loaded:
            return _edit_cache
        if EDIT_HISTORY_PATH.exists():
            try:
                txt = EDIT_HISTORY_PATH.read_text("utf-8")
                if txt.strip():
                    data = json.loads(txt)
                    if isinstance(data, dict):
                        _edit_cache = data
                        print(f"[edits] loaded {len(_edit_cache)} items from {EDIT_HISTORY_PATH}")
                    else:
                        print(f"[edits] warning: file {EDIT_HISTORY_PATH} is not a dict")
            except Exception as e:
                print(f"[edits] load error (file exists but failed to read): {e}")
                # DON'T set _edit_loaded = True here if we want to try again,
                # but for safety let's not overwrite an empty cache to disk yet.
                return _edit_cache
        else:
            print(f"[edits] no history file at {EDIT_HISTORY_PATH}, starting fresh")
            _edit_cache = {}
            
        _edit_loaded = True
        return _edit_cache

def edits_save():
    global _edit_loaded
    if not _edit_loaded:
        print("[edits] refuse to save: cache not loaded yet (prevents data loss)")
        return
    with _edit_lock:
        try:
            # Use absolute path to ensure we are writing where we expect
            abs_path = EDIT_HISTORY_PATH.absolute()
            tmp = abs_path.with_suffix(".json.tmp")
            
            data_str = json.dumps(_edit_cache, indent=2, sort_keys=True, ensure_ascii=False)
            tmp.write_text(data_str, encoding="utf-8")
            
            # Verify file was written before replacing
            if tmp.exists() and tmp.stat().st_size > 0:
                os.replace(tmp, abs_path)
            elif not _edit_cache:
                # If cache is empty, we allow writing if it's intentional (e.g. clear)
                # but we should still check if the write succeeded (0 bytes for empty dict is {} -> 2 bytes)
                if tmp.exists() and tmp.stat().st_size >= 2:
                    os.replace(tmp, abs_path)
            else:
                print(f"[edits] save warning: tmp file is empty, aborted replace to {abs_path}")
                
        except Exception as e:
            print(f"[edits] save error: {e}")

def edits_apply(artist, track, album):
    """ถ้าเคยแก้ไว้ → คืนค่าที่แก้แล้ว; ไม่งั้นคืนของเดิม"""
    edits_load()
    key = f"{artist}||||{track}"
    with _edit_lock:
        e = _edit_cache.get(key)
    if not e:
        return artist, track, album, None
    return (
        e.get("artist", artist),
        e.get("track", track),
        e.get("album", album),
        e.get("media")
    )

def edits_upsert(original_artist, original_track, artist, track, album, media=None):
    edits_load()
    key = f"{original_artist}||||{original_track}"
    with _edit_lock:
        _edit_cache[key] = {
            "artist": artist,
            "track": track,
            "album": album,
            "media": media,
            "timestamp": str(time.time())
        }
    edits_save()

def edits_delete(key):
    edits_load()
    with _edit_lock:
        existed = key in _edit_cache
        if existed:
            _edit_cache.pop(key, None)
    if existed:
        edits_save()
    return existed

def edits_replace(new_dict):
    global _edit_cache, _edit_loaded
    with _edit_lock:
        _edit_cache = dict(new_dict)
        _edit_loaded = True
    edits_save()

def edits_list():
    edits_load()
    with _edit_lock:
        items = []
        for key, v in _edit_cache.items():
            parts = key.split("||||", 1)
            orig_artist = parts[0] if parts else ""
            orig_track = parts[1] if len(parts) > 1 else ""
            items.append({
                "key": key,
                "original_artist": orig_artist,
                "original_track": orig_track,
                "artist": v.get("artist", ""),
                "track": v.get("track", ""),
                "album": v.get("album", ""),
                "media": v.get("media"),
                "timestamp": float(v.get("timestamp", 0) or 0)
            })
    items.sort(key=lambda x: x["timestamp"], reverse=True)
    return items

def is_edit_history_format(obj):
    """ตรวจว่า JSON ที่ import มาเป็น edit history format หรือไม่ — ดูจาก key มี `||||` และ value เป็น dict ที่มี track/artist"""
    if not isinstance(obj, dict):
        return False
    if not obj:
        return False
    # อย่าให้ทับซ้อนกับ events export format
    if "events" in obj and isinstance(obj.get("events"), list):
        return False
    for k, v in obj.items():
        if "||||" in k and isinstance(v, dict) and ("track" in v or "artist" in v):
            return True
        break
    return False

# ============================================================
# Database
# ============================================================
_db_lock = threading.Lock()

def db_init():
    with _db_lock:
        conn = sqlite3.connect(DB_PATH)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp INTEGER NOT NULL,
                event_type TEXT NOT NULL,
                track_name TEXT NOT NULL,
                artist_name TEXT NOT NULL,
                album_name TEXT,
                duration REAL,
                position REAL
            )
        """)
        conn.execute("CREATE INDEX IF NOT EXISTS idx_events_time ON events(timestamp DESC)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_events_track ON events(artist_name, track_name)")
        conn.commit()
        conn.close()

def db_insert(event_type, track):
    with _db_lock:
        conn = sqlite3.connect(DB_PATH)
        conn.execute(
            "INSERT INTO events (timestamp, event_type, track_name, artist_name, album_name, duration, position) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (int(time.time()), event_type, track["name"], track["artist"], track.get("album", ""), track.get("duration", 0), track.get("position", 0))
        )
        conn.commit()
        conn.close()

def db_recent(limit=50):
    with _db_lock:
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM events ORDER BY timestamp DESC LIMIT ?",
            (limit,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]

def db_all():
    with _db_lock:
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        rows = conn.execute("SELECT * FROM events ORDER BY timestamp ASC").fetchall()
        conn.close()
        return [dict(r) for r in rows]

def db_bulk_insert(events):
    inserted = 0
    with _db_lock:
        conn = sqlite3.connect(DB_PATH)
        for e in events:
            try:
                conn.execute(
                    "INSERT INTO events (timestamp, event_type, track_name, artist_name, album_name, duration, position) VALUES (?, ?, ?, ?, ?, ?, ?)",
                    (int(e["timestamp"]), e["event_type"], e["track_name"], e["artist_name"], e.get("album_name", "") or "", float(e.get("duration") or 0), float(e.get("position") or 0))
                )
                inserted += 1
            except Exception:
                pass
        conn.commit()
        conn.close()
    return inserted

def db_clear():
    with _db_lock:
        conn = sqlite3.connect(DB_PATH)
        conn.execute("DELETE FROM events")
        conn.commit()
        conn.close()

# ============================================================
# Apple Music query
# ============================================================
def query_music():
    """
    คืนค่า:
    - dict เมื่ออ่านได้ + state = playing/paused
    - "stopped" (str) เมื่อรู้แน่ว่า Music หยุด/ไม่เปิด
    - None เมื่ออ่านไม่ได้ (osascript fail / transient error) — caller ควร keep last state
    """
    try:
        # บังคับ Environment ให้เป็น UTF-8
        env = os.environ.copy()
        env["LANG"] = "en_US.UTF-8"
        
        r = subprocess.run(
            ["osascript", "-e", FETCH_STATE_SCRIPT],
            capture_output=True, 
            text=False, # อ่านเป็น bytes แทนเพื่อมา decode เอง
            timeout=5,
            env=env
        )
        
        if r.returncode != 0:
            err_msg = r.stderr.decode("utf-8", errors="replace").strip()
            print(f"\n[debug] osascript error (code {r.returncode}): {err_msg}")
            return None
            
        # พยายาม decode ด้วย utf-8 ถ้าไม่ได้ให้ใช้ mac_roman (fallback สำหรับ AppleScript)
        try:
            out = r.stdout.decode("utf-8").strip()
        except UnicodeDecodeError:
            out = r.stdout.decode("mac_roman").strip()
            
        if not out:
            return None
            
        print(f"\n[debug] raw output: '{out}'")
        
        parts = out.split("|")
        if len(parts) < 6:
            print(f"\n[debug] parse error (parts={len(parts)}): {out}")
            return None
            
        state, pos, dur, name, artist, album = parts[0], parts[1], parts[2], parts[3], parts[4], parts[5]
        
        # กรองสถานะ
        if state == "stopped":
            return "stopped"
            
        if not name or not artist:
            print(f"\n[debug] missing metadata: name='{name}', artist='{artist}'")
            return None

        return {
            "state": state,
            "position": float(pos or 0),
            "duration": float(dur or 0),
            "name": name.strip(),
            "artist": artist.strip(),
            "album": album.strip(),
            "playing": state == "playing"
        }
    except subprocess.TimeoutExpired:
        print("\n[debug] osascript timeout")
        return None
    except Exception as e:
        print(f"\n[debug] query_music exception: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        return None

# ============================================================
# Artwork (iTunes Search API + uncompressed cover fallback)
# ============================================================
# ทำงานคล้าย Music-Scrobbler: normalize query, best-match filter, hi-res fallback
_artwork_cache = {}
_artwork_cache_order = []
_artwork_lock = threading.Lock()
_ARTWORK_CACHE_MAX = 50

def _artwork_cache_get(key):
    with _artwork_lock:
        return _artwork_cache.get(key)

def _artwork_cache_put(key, value):
    with _artwork_lock:
        if key in _artwork_cache:
            _artwork_cache_order.remove(key)
        _artwork_cache[key] = value
        _artwork_cache_order.append(key)
        while len(_artwork_cache_order) > _ARTWORK_CACHE_MAX:
            old = _artwork_cache_order.pop(0)
            _artwork_cache.pop(old, None)

def _artwork_cache_invalidate(artist, track, album=""):
    key = f"{(artist or '').lower()}|{(track or '').lower()}|{(album or '').lower()}"
    with _artwork_lock:
        _artwork_cache.pop(key, None)
        if key in _artwork_cache_order:
            _artwork_cache_order.remove(key)

def _itunes_query_term(artist, track, album):
    terms = []
    for t in (track, artist, album):
        t = (t or "").strip()
        if not t:
            continue
        terms.append(" ".join(t.split()))
    return " ".join(terms)

def _itunes_search(artist, track, album):
    term = _itunes_query_term(artist, track, album)
    if not term:
        term = f"{artist} {album}".strip()
    if not term:
        return []
    params = [
        ("term", term),
        ("media", "music"),
        ("entity", "musicTrack"),
        ("limit", "10"),
    ]
    if (track or "").strip():
        params.append(("attribute", "songTerm"))
    url = "https://itunes.apple.com/search?" + urllib.parse.urlencode(params)
    print(f"[artwork] search url: {url}")
    try:
        with urllib.request.urlopen(url, timeout=5) as r:
            data = json.loads(r.read().decode())
        return data.get("results", []) or []
    except Exception as e:
        print(f"[artwork] itunes error: {e}")
        return []

def _pick_best_result(results, artist, track, album):
    a, t, al = (artist or "").lower(), (track or "").lower(), (album or "").lower()
    for item in results:
        artist_match = (item.get("artistName") or "").lower() == a
        track_match = (item.get("trackName") or "").lower() == t
        album_match = True if not al else (al in (item.get("collectionName") or "").lower())
        if artist_match and track_match and album_match:
            return item
    return results[0] if results else None

def _fetch_cover_details(collection_view_url):
    """คืน (uncompressed_cover_url, master_tall_url) จาก api.aritra.ovh/v1/covers"""
    if not collection_view_url:
        return (None, None)
    try:
        q = urllib.parse.urlencode({"url": collection_view_url})
        url = f"https://api.aritra.ovh/v1/covers?{q}"
        print(f"[artwork] hi-res search url: {url}")
        with urllib.request.urlopen(url, timeout=5) as r:
            data = json.loads(r.read().decode())
        uc = (data or {}).get("uncompressed_cover_art") or {}
        master = (data or {}).get("master") or {}
        return (uc.get("url") or None, master.get("tall") or None)
    except Exception:
        return (None, None)

def _scrape_apple_m3u8_url(track_view_url):
    """ขูดหน้า Apple Music เพื่อหา URL ของ master.m3u8 playlist"""
    if not track_view_url:
        return None
    try:
        req = urllib.request.Request(
            track_view_url,
            headers={
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
            }
        )
        with urllib.request.urlopen(req, timeout=5) as r:
            html = r.read().decode('utf-8', errors='ignore')
        
        # Regex สำหรับหา URL ของ Apple Video ในหน้า HTML
        m3u8_regex = r'https://mvod\.itunes\.apple\.com/[^\s"\\\'\)]+\.m3u8'
        matches = re.findall(m3u8_regex, html)
        if not matches:
            return None
            
        # กำจัดตัวซ้ำ
        unique_matches = list(dict.fromkeys(matches))
        # ค้นหาตัวที่เป็น 'default.m3u8' หรือ 'main.m3u8'
        for m in unique_matches:
            if 'default.m3u8' in m or 'main.m3u8' in m:
                return m
        return unique_matches[0]
    except Exception as e:
        print(f"[artwork] scrape m3u8 error: {e}")
        return None

def _parse_apple_m3u8_to_mp4s(master_url):
    """ดึง master playlist และแปลง .m3u8 เป็น .mp4 URLs แยกตามความละเอียด"""
    if not master_url:
        return {}
    try:
        print(f"[artwork] fetching master playlist: {master_url}")
        req = urllib.request.Request(master_url)
        with urllib.request.urlopen(req, timeout=5) as r:
            text = r.read().decode('utf-8', errors='ignore')
        
        lines = text.splitlines()
        results = {}
        for line in lines:
            clean = line.strip()
            if clean.startswith('https://') and clean.endswith('.m3u8'):
                mp4_url = clean.replace('.m3u8', '-.mp4')
                
                if '2160x2160' in clean:
                    results["4K (2160p)"] = mp4_url
                elif '1080x1080' in clean:
                    results["Full HD (1080p)"] = mp4_url
                elif '768x768' in clean:
                    results["HD (768p)"] = mp4_url
                elif '486x486' in clean:
                    results["SD (486p)"] = mp4_url
        return results
    except Exception as e:
        print(f"[artwork] parse m3u8 error: {e}")
        return {}

def _fetch_animated_artwork_new(track_view_url):
    """Logic ใหม่: Scrape -> Parse -> Pick best resolution"""
    master_url = _scrape_apple_m3u8_url(track_view_url)
    if not master_url:
        return None
        
    mp4s = _parse_apple_m3u8_to_mp4s(master_url)
    if not mp4s:
        return None
        
    # ลำดับความสำคัญที่เลือก: 1080p > 4K > 768p > 486p
    priority = ["Full HD (1080p)", "4K (2160p)", "HD (768p)", "SD (486p)"]
    for p in priority:
        if p in mp4s:
            print(f"[artwork] picked resolution: {p} -> {mp4s[p]}")
            return mp4s[p]
    
    # ถ้าไม่มีในลิสต์ เอาตัวแรกที่มี
    return next(iter(mp4s.values())) if mp4s else None

def _fetch_animated_artwork(collection_view_url):
    """คืน animation URL (mp4) — ลองแบบขูดก่อน ถ้าไม่ได้ให้ fallback ไป dodoapps"""
    if not collection_view_url:
        return None
    
    # 1. ลองแบบขูดหน้าเว็บ Apple Music โดยตรง (New logic)
    try:
        new_url = _fetch_animated_artwork_new(collection_view_url)
        if new_url:
            return new_url
    except Exception as e:
        print(f"[artwork] new logic failed: {e}")

    # 2. Fallback ไป clients.dodoapps.io (Old logic)
    try:
        body = urllib.parse.urlencode({
            "url": collection_view_url,
            "animation": "true",
        }).encode("utf-8")
        print(f"[artwork] fallback animation search: https://clients.dodoapps.io/playlist-precis/playlist-artwork.php")
        req = urllib.request.Request(
            "https://clients.dodoapps.io/playlist-precis/playlist-artwork.php",
            data=body,
            method="POST",
            headers={
                "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
                "Accept": "application/json",
            },
        )
        with urllib.request.urlopen(req, timeout=5) as r:
            data = json.loads(r.read().decode())
        return (data or {}).get("animatedUrl1080") or (data or {}).get("animatedUrl") or None
    except Exception as e:
        print(f"[artwork] fallback logic failed: {e}")
        return None

def _sanitize_apple_music_url(raw_url, drop_track_identifier=False):
    """ตัด query parameter `uo` (และ `i` ถ้าเป็น albumUrl) ให้เหมือน Music-Scrobbler"""
    if not raw_url:
        return None
    try:
        parts = urllib.parse.urlparse(raw_url)
        qs = urllib.parse.parse_qsl(parts.query, keep_blank_values=True)
        filtered = []
        for k, v in qs:
            kl = k.lower()
            if kl == "uo":
                continue
            if drop_track_identifier and kl == "i":
                continue
            filtered.append((k, v))
        new_q = urllib.parse.urlencode(filtered)
        return urllib.parse.urlunparse(parts._replace(query=new_q))
    except Exception:
        return raw_url

def fetch_media_urls(artist, track, album=""):
    """คืน dict ของ media URLs เหมือน Music-Scrobbler: artwork/animation/masterTall/track/album/artist"""
    key = f"{(artist or '').lower()}|{(track or '').lower()}|{(album or '').lower()}"
    cached = _artwork_cache_get(key)
    if cached is not None:
        return cached

    empty = {"artwork": None, "animation": None, "masterTall": None,
             "track": None, "album": None, "artist": None}

    results = _itunes_search(artist, track, album)
    best = _pick_best_result(results, artist, track, album)
    if not best:
        _artwork_cache_put(key, empty)
        return empty

    # artwork base (100 → 600)
    art_url = None
    small = best.get("artworkUrl100") or ""
    if small:
        art_url = small.replace("100x100bb.jpg", "600x600bb.jpg")

    track_url = best.get("trackViewUrl") or None
    album_url = best.get("collectionViewUrl") or None
    artist_url = best.get("artistViewUrl") or None

    # ดึง uncompressed cover + master.tall + animation ถ้ามี albumUrl
    master_tall_url = None
    animation_url = None
    if album_url:
        hi, master_tall_url = _fetch_cover_details(album_url)
        if hi:
            art_url = hi
        animation_url = _fetch_animated_artwork(album_url)

    media = {
        "artwork": art_url,
        "animation": animation_url,
        "masterTall": master_tall_url,
        "track": _sanitize_apple_music_url(track_url, drop_track_identifier=False),
        "album": _sanitize_apple_music_url(album_url, drop_track_identifier=True),
        "artist": artist_url,
    }
    _artwork_cache_put(key, media)
    return media

def fetch_artwork(artist, track, album=""):
    """backward-compat: คืนเฉพาะ artwork URL"""
    return (fetch_media_urls(artist, track, album) or {}).get("artwork")

# ============================================================
# Notifications (macOS)
# ============================================================
# callback ให้ app.py (menubar app) hook เพื่อส่ง notification แบบ native
# ถ้าไม่ hook จะ fallback ไป osascript
NOTIFY_CALLBACK = {"fn": None}

# callback ให้ app.py hook action จาก mini player popover
# key: "quit" | "open_window" | "open_settings"
APP_CALLBACKS = {"quit": None, "open_window": None, "open_settings": None}

def _osascript_notify(title: str, subtitle: str, body: str = "", image_url: str = ""):
    # osascript แสดงรูปไม่ได้ — ignore image_url
    try:
        def esc(x):
            return str(x).replace("\\", "\\\\").replace('"', '\\"')
        script = (
            f'display notification "{esc(body)}" '
            f'with title "{esc(title)}" '
            f'subtitle "{esc(subtitle)}"'
        )
        subprocess.Popen(
            ["osascript", "-e", script],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
        )
    except Exception as e:
        print(f"[notify] osascript error: {e}")

def notify(title: str, subtitle: str = "", body: str = "", image_url: str = ""):
    fn = NOTIFY_CALLBACK.get("fn")
    if fn:
        try:
            # callback ใหม่รับ image_url — ถ้าเป็นเวอร์ชันเก่าจะ TypeError → fallback
            try:
                fn(title, subtitle, body, image_url)
            except TypeError:
                fn(title, subtitle, body)
            return
        except Exception as e:
            print(f"[notify] callback error: {e}")
    _osascript_notify(title, subtitle, body, image_url)

def _notify_event(kind: str, track: dict, artwork_url: str = ""):
    s = load_settings().get("notifications", DEFAULT_SETTINGS["notifications"])
    if not s.get("enabled", True):
        return
    if kind in ("play", "replay") and not s.get("on_play", True):
        return
    if kind == "scrobble" and not s.get("on_scrobble", False):
        return
    name = track.get("name") or "—"
    artist = track.get("artist") or ""
    album = track.get("album") or ""
    if kind == "scrobble":
        notify("✓ Scrobbled", f"{name}", f"{artist} · {album}" if album else artist, artwork_url)
    else:
        label = "▶ Now Playing" if kind == "play" else "↻ Replay"
        notify(label, name, f"{artist} · {album}" if album else artist, artwork_url)

# ============================================================
# Last.fm
# ============================================================
def start_server(port, data_dir):
    print(f"\n{'='*50}")
    print(f"  APPLE MUSIC SCROBBLER SERVER v{__version__} STARTING")
    print(f"  Data Dir: {data_dir}")
    print(f"{'='*50}\n")
    
    server_address = ('', port)

def lastfm_sign(params, secret):
    keys = sorted(k for k in params if k != "format" and k != "callback")
    raw = "".join(f"{k}{params[k]}" for k in keys) + secret
    return hashlib.md5(raw.encode("utf-8")).hexdigest()

def lastfm_call(method, params, secret=None, post=False):
    params = dict(params)
    params["method"] = method
    if secret:
        params["api_sig"] = lastfm_sign(params, secret)
    params["format"] = "json"
    url = "https://ws.audioscrobbler.com/2.0/"
    try:
        if post:
            data = urllib.parse.urlencode(params).encode()
            req = urllib.request.Request(url, data=data, method="POST")
        else:
            req = urllib.request.Request(url + "?" + urllib.parse.urlencode(params))
        with urllib.request.urlopen(req, timeout=8) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        try:
            return json.loads(e.read().decode())
        except Exception:
            return {"error": -1, "message": str(e)}
    except Exception as e:
        return {"error": -1, "message": str(e)}

def lastfm_now_playing(track):
    s = load_settings()["lastfm"]
    if not (s["enabled"] and s["session_key"] and s["api_key"] and s["api_secret"]):
        return
    params = {
        "api_key": s["api_key"],
        "sk": s["session_key"],
        "track": track["name"],
        "artist": track["artist"],
        "album": track.get("album", ""),
        "duration": str(int(track.get("duration", 0)))
    }
    lastfm_call("track.updateNowPlaying", params, s["api_secret"], post=True)

def lastfm_scrobble(track, start_ts):
    s = load_settings()["lastfm"]
    if not (s["enabled"] and s["session_key"] and s["api_key"] and s["api_secret"]):
        return False
    params = {
        "api_key": s["api_key"],
        "sk": s["session_key"],
        "track": track["name"],
        "artist": track["artist"],
        "album": track.get("album", ""),
        "timestamp": str(int(start_ts)),
        "duration": str(int(track.get("duration", 0)))
    }
    res = lastfm_call("track.scrobble", params, s["api_secret"], post=True)
    return "scrobbles" in res

# ============================================================
# Webhook (payload shape = Music-Scrobbler WebhookService)
# ============================================================
_last_webhook_ts = 0

def get_last_webhook_ts():
    return _last_webhook_ts
# map event ภายใน (5 ตัว) → eventName ที่ Music-Scrobbler ใช้ (3 ตัว)
_WEBHOOK_EVENT_MAP = {
    "play":     "nowplaying",
    "replay":   "nowplaying",
    "resume":   "nowplaying",
    "pause":    "paused",
    "stopped":  "paused",
    "scrobble": "scrobble",
    "nowplaying": "nowplaying",
}

def build_webhook_payload(event_type, track, media=None):
    event_name = _WEBHOOK_EVENT_MAP.get(event_type, event_type)
    is_playing = (event_name != "paused")
    m = media or {}
    artwork_str = m.get("artwork") or ""
    animation_str = m.get("animation") or ""
    tall_video_str = m.get("masterTall") or ""
    track_url_str = m.get("track") or ""
    album_url_str = m.get("album") or ""
    artist_url_str = m.get("artist") or ""

    # primaryMediaUrl: animation > tall > artwork (เหมือน WebhookService.swift)
    if animation_str:
        primary_media_url, primary_media_type = animation_str, "video"
    elif tall_video_str:
        primary_media_url, primary_media_type = tall_video_str, "video"
    elif artwork_str:
        primary_media_url, primary_media_type = artwork_str, "image"
    else:
        primary_media_url, primary_media_type = "", ""

    duration_i = int(track.get("duration", 0) or 0)
    position_i = int(track.get("position", 0) or 0)

    return {
        "eventName": event_name,
        "time": int(time.time() * 1000),
        "data": {
            "song": {
                "processed": {
                    "artist": track["artist"],
                    "track": track["name"],
                    "album": track.get("album", ""),
                    "duration": duration_i
                },
                "parsed": {
                    "artist": track["artist"],
                    "track": track["name"],
                    "duration": duration_i,
                    "currentTime": position_i,
                    "isPlaying": is_playing
                },
                "flags": {"isValid": True},
                "metadata": {
                    "label": "Apple Music Scrobbler",
                    "trackArtUrl": artwork_str,
                    "animationUrl": animation_str,
                    "masterTallUrl": tall_video_str,
                    "trackUrl": track_url_str,
                    "albumUrl": album_url_str,
                    "artistUrl": artist_url_str,
                    "primaryMediaUrl": primary_media_url,
                    "primaryMediaType": primary_media_type
                },
                "connector": {"label": "Apple Music"}
            }
        }
    }

def send_webhook(event_type, track, media=None):
    global _last_webhook_ts
    s = load_settings()["webhook"]
    if not s["enabled"]:
        return
    urls = s.get("urls", [])
    if not urls:
        return
        
    _last_webhook_ts = time.time()
    payload = build_webhook_payload(event_type, track, media)
    payload_data = json.dumps(payload).encode()
    
    def _fire(url):
        print(f"[webhook] sending to {url}: {json.dumps(payload, indent=2, ensure_ascii=False)}")
        try:
            req = urllib.request.Request(url, data=payload_data, method="POST",
                                         headers={"Content-Type": "application/json"})
            urllib.request.urlopen(req, timeout=5)
        except Exception as e:
            print(f"[webhook] error ({url}): {e}")

    for url in urls:
        if url.strip():
            threading.Thread(target=_fire, args=(url.strip(),), daemon=True).start()


# ============================================================
# Tracker (background thread)
# ============================================================
class Tracker:
    MAX_MISS_BEFORE_CLEAR = 3  # ทน osascript พลาดได้ 3 รอบ (~6 วิ) ก่อนจะล้าง UI
    STOPPED_CONFIRM_COUNT = 2  # ต้องเห็น stopped ติดกันสองครั้งก่อนจะเชื่อว่าหยุดจริง

    def __init__(self):
        self.last_track_id = ""
        self.last_position = 0.0
        self.last_state = "stopped"
        self.track_start_ts = 0
        self.has_scrobbled = False
        # track_id ล่าสุดที่ scrobble ไปแล้ว — ใช้กันไม่ให้ scrobble ซ้ำเมื่อ pause/play เพลงเดิม
        # จะถูกล้างเมื่อ replay (เริ่มใหม่จากต้น) หรือเมื่อ Music หยุดจริง
        self.last_scrobbled_track_id = ""
        self.current_artwork_url = None
        self.current_media = {}
        # เก็บชื่อทั้งก่อน/หลัง apply edits — ใช้ตอน reload/edit จาก UI
        self.current_original = {"artist": "", "track": "", "album": ""}
        self.current_edited = {"artist": "", "track": "", "album": ""}
        self.stop_event = threading.Event()
        # debounce state
        self.last_good_payload = None
        self.miss_count = 0
        self.stopped_count = 0

    def run(self):
        while not self.stop_event.is_set():
            try:
                self.tick()
            except Exception as e:
                print(f"[tracker] error: {e}")
            self.stop_event.wait(2.0)

    def stop(self):
        self.stop_event.set()

    def tick(self):
        # Heartbeat log for debugging bundle issues
        print(".", end="", flush=True) 
        
        info = query_music()

        # osascript fail / parse ไม่ได้ → ค้างสถานะเดิมไว้ก่อน
        if info is None:
            self.miss_count += 1
            if self.miss_count >= self.MAX_MISS_BEFORE_CLEAR:
                self.last_good_payload = None
                self._write_now_playing({"playing": False})
            # ถ้ายังไม่เกิน threshold ไม่เขียนอะไรใหม่ — คง snapshot เดิม
            return

        # Music หยุดจริง ๆ — ต้องเห็นติดกันถึงจะเชื่อ
        if info == "stopped":
            self.miss_count = 0
            self.stopped_count += 1
            if self.stopped_count >= self.STOPPED_CONFIRM_COUNT:
                # ถ้าเคยเล่นอยู่ ให้ยิง pause ไปบอก webhook ด้วย
                if self.last_state == "playing" and self.last_good_payload:
                    self._fire("stopped", self.last_good_payload)

                self.last_good_payload = None
                self.last_track_id = ""
                self.last_scrobbled_track_id = ""
                self.last_state = "stopped"
                self._write_now_playing({"playing": False})
            return

        # รอบนี้อ่านได้สมบูรณ์ — reset counter
        self.miss_count = 0
        self.stopped_count = 0

        # ใช้ edit history แก้ชื่อ artist/track/album ก่อนที่จะใช้งานต่อ
        edited_artist, edited_track, edited_album, pinned_media = edits_apply(
            info["artist"], info["name"], info["album"]
        )
        self.current_original = {"artist": info["artist"], "track": info["name"], "album": info["album"]}
        self.current_edited = {"artist": edited_artist, "track": edited_track, "album": edited_album}

        track_id = f"{edited_track} - {edited_artist}"
        state = info["state"]
        is_playing = info["playing"]

        is_new = track_id != self.last_track_id
        is_replay = (not is_new) and info["position"] < 3.0 and self.last_position > 5.0

        track_payload = {
            "name": edited_track,
            "artist": edited_artist,
            "album": edited_album,
            "duration": info["duration"],
            "position": info["position"]
        }

        if is_playing and (is_new or is_replay):
            evt = "replay" if is_replay else "play"
            # DB + Last.fm now_playing ยิงทันที — webhook + notification รอ media ก่อน (ได้ artwork)
            db_insert(evt, track_payload)
            threading.Thread(target=lastfm_now_playing, args=(track_payload,), daemon=True).start()
            print(f"[event] {evt}: {track_payload['name']} — {track_payload['artist']}")
            self.last_track_id = track_id
            self.track_start_ts = int(time.time()) - int(info["position"])
            self.has_scrobbled = False
            # เฉพาะ replay เท่านั้นที่อนุญาตให้ scrobble เพลงเดิมได้อีกครั้ง
            # สำหรับเพลงใหม่ (is_new) track_id จะต่างอยู่แล้ว จึงไม่จำเป็นต้องล้าง
            if is_replay:
                self.last_scrobbled_track_id = ""
            self.current_artwork_url = (pinned_media or {}).get("artwork")
            self.current_media = pinned_media or {}
            threading.Thread(
                target=self._prefetch_and_fire_webhook,
                args=(evt, edited_artist, edited_track, edited_album, track_payload, track_id, pinned_media),
                daemon=True
            ).start()
        elif is_playing and self.last_state == "paused":
            self._fire("resume", track_payload)
        elif (not is_playing) and self.last_state == "playing":
            self._fire("pause", track_payload)

        # กันซ้ำ: เพลงที่เคย scrobble แล้วจะไม่ส่งอีก จนกว่าจะ replay (เริ่มใหม่จากต้น) หรือเปลี่ยนเพลง
        if (is_playing and not self.has_scrobbled
                and track_id != self.last_scrobbled_track_id
                and info["duration"] > 30):
            s = load_settings()["scrobble"]
            pct = (info["position"] / info["duration"]) * 100 if info["duration"] > 0 else 0
            if pct >= s["percent"] or info["position"] >= 240:
                if info["position"] >= s["min_seconds"]:
                    self.has_scrobbled = True
                    self.last_scrobbled_track_id = track_id
                    self._fire("scrobble", track_payload)
                    threading.Thread(target=lastfm_scrobble, args=(track_payload, self.track_start_ts), daemon=True).start()
                    threading.Thread(target=_notify_event, args=("scrobble", track_payload, self.current_artwork_url or ""), daemon=True).start()

        self.last_state = state
        self.last_position = info["position"]

        payload = {
            "playing": is_playing,
            "name": edited_track,
            "artist": edited_artist,
            "album": edited_album,
            "original_name": info["name"],
            "original_artist": info["artist"],
            "original_album": info["album"],
            "duration": info["duration"],
            "position": info["position"],
            "artwork_url": self.current_artwork_url,
            "animation_url": (self.current_media or {}).get("animation"),
            "has_scrobbled": self.has_scrobbled,
            "scrobble_percent": (info["position"] / info["duration"] * 100) if info["duration"] > 0 else 0
        }
        
        # Webhook heartbeat logic
        s_webhook = load_settings()["webhook"]
        hb = s_webhook.get("heartbeat_seconds", 0)
        if is_playing and s_webhook["enabled"] and hb > 0:
            if time.time() - get_last_webhook_ts() >= hb:
                self._fire("nowplaying", track_payload, record_db=False)

        self.last_good_payload = payload
        self._write_now_playing(payload)

    def _fire(self, event_type, track, record_db=True):
        """ยิง event สำหรับ resume/pause/scrobble — ใช้ media ที่ prefetch ไว้แล้ว"""
        if record_db:
            db_insert(event_type, track)
        media = dict(self.current_media) if self.current_media else {}
        threading.Thread(target=send_webhook, args=(event_type, track, media), daemon=True).start()
        print(f"[event] {event_type}: {track['name']} — {track['artist']}")

    def _prefetch_and_fire_webhook(self, event_type, artist, track, album, track_payload, track_id, pinned_media=None):
        """ดึง media URLs → อัปเดต state → ยิง webhook (เลียน Music-Scrobbler)"""
        if pinned_media:
            media = pinned_media
        else:
            media = fetch_media_urls(artist, track, album) or {}
        
        # เพลงเปลี่ยนระหว่างรอ network → ทิ้ง
        if track_id != self.last_track_id:
            return
        self.current_media = media
        self.current_artwork_url = media.get("artwork")
        self._update_now_playing_artwork()
        send_webhook(event_type, track_payload, media)
        # ยิง notification หลังได้ artwork แล้ว — ให้รูปโชว์ใน notification ได้
        if event_type in ("play", "replay"):
            threading.Thread(
                target=_notify_event,
                args=(event_type, track_payload, self.current_artwork_url or ""),
                daemon=True
            ).start()

    def _update_now_playing_artwork(self):
        """อัปเดต artwork_url ใน snapshot ปัจจุบันให้ UI เห็นภาพใหม่โดยไม่ต้องรอ tick ถัดไป"""
        cur = dict(CURRENT_NOW_PLAYING.get("data") or {})
        if not cur.get("playing") and not cur.get("name"):
            return
        cur["artwork_url"] = self.current_artwork_url
        self._write_now_playing(cur)

    def reload_media(self):
        """invalidate cache แล้วดึง media URLs ใหม่สำหรับเพลงที่กำลังเล่น"""
        # 1. Re-apply edits ทันที เผื่อ user เพิ่งบันทึกไป
        artist, track, album, pinned_media = edits_apply(
            self.current_original["artist"], 
            self.current_original["track"], 
            self.current_original.get("album", "")
        )
        
        # 2. Update internal state เพื่อให้ tick ถัดไปไม่มองว่าเป็นเพลงใหม่ (is_new)
        self.current_edited = {"artist": artist, "track": track, "album": album}
        self.last_track_id = f"{track} - {artist}"
        
        # 3. ล้าง cache artwork เดิม
        _artwork_cache_invalidate(artist, track, album)
        
        track_payload = {
            "name": track,
            "artist": artist,
            "album": album,
            "duration": 0,
            "position": 0,
        }
        
        # 4. Prefetch media และยิง webhook/nowplaying ใหม่
        threading.Thread(
            target=self._prefetch_and_fire_webhook,
            args=("play", artist, track, album,
                  track_payload, self.last_track_id, pinned_media),
            daemon=True
        ).start()
        return True

    def _write_now_playing(self, data):
        # เก็บใน memory ให้ API อ่านได้ทันที (ไม่ race กับการเขียนไฟล์)
        CURRENT_NOW_PLAYING["data"] = data
        # เขียนไฟล์แบบ atomic: เขียน tmp แล้ว rename (os.replace เป็น atomic บน POSIX)
        try:
            tmp = NOW_PLAYING_PATH.with_suffix(".json.tmp")
            tmp.write_text(json.dumps(data))
            os.replace(tmp, NOW_PLAYING_PATH)
        except Exception:
            pass

# ============================================================
# HTTP server
# ============================================================
class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        # เสิร์ฟไฟล์ static (index.html, settings.html, i18n.js) จาก web/
        super().__init__(*args, directory=str(WEB_DIR), **kwargs)

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path

        if path == "/api/nowplaying":
            return self._json(CURRENT_NOW_PLAYING.get("data", {"playing": False}))
        if path == "/api/settings":
            return self._json(public_settings())
        if path == "/api/history":
            qs = urllib.parse.parse_qs(parsed.query)
            limit = int(qs.get("limit", ["50"])[0])
            return self._json({"events": db_recent(limit)})
        if path == "/api/export":
            qs = urllib.parse.parse_qs(parsed.query)
            fmt = qs.get("format", ["json"])[0]
            return self._export(fmt)
        if path == "/api/edits":
            return self._json({"items": edits_list()})
        if path == "/api/edits/export":
            edits_load()
            body = json.dumps(_edit_cache, indent=2, sort_keys=True, ensure_ascii=False).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Disposition", f"attachment; filename=MusicScrobblerEdits_{int(time.time())}.json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return

        if path == "/api/artwork/search":
            qs = urllib.parse.parse_qs(parsed.query)
            term = qs.get("term", [""])[0]
            artist = qs.get("artist", [""])[0]
            track = qs.get("track", [""])[0]
            
            if not term and artist and track:
                term = f"{artist} {track}"
            
            if not term:
                return self._json({"results": []})
            
            results = _itunes_search(artist or term, track or term, "")
            formatted = []
            for item in results:
                # แปลง result จาก iTunes ให้เป็น media payload ที่เราใช้
                small = item.get("artworkUrl100") or ""
                art_url = small.replace("100x100bb.jpg", "600x600bb.jpg")
                
                track_url = item.get("trackViewUrl")
                album_url = item.get("collectionViewUrl")
                artist_url = item.get("artistViewUrl")
                
                # เราไม่ fetch animation ทันทีเพราะมันช้า (ค่อย fetch ตอนเลือกแล้ว)
                # หรือถ้าอยากให้เห็นใน modal เลยก็ต้อง fetch ตรงนี้
                # เพื่อความเร็ว เราจะ fetch เฉพาะ artwork ก่อนใน modal
                formatted.append({
                    "artist": item.get("artistName"),
                    "track": item.get("trackName"),
                    "album": item.get("collectionName"),
                    "artwork": art_url,
                    "itunes_url": album_url, # ใช้เก็บไว้ fetch animation ทีหลัง
                    "raw": item # เก็บ raw เผื่อใช้ metadata อื่นๆ
                })
            return self._json({"results": formatted})
        return super().do_GET()

    def do_POST(self):
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path

        if path == "/control":
            qs = urllib.parse.parse_qs(parsed.query)
            action = qs.get("action", [""])[0]
            script = CONTROL_SCRIPTS.get(action)
            if not script:
                return self._json({"ok": False, "error": "unknown action"}, status=400)
            try:
                subprocess.run(["osascript", "-e", script], check=True, timeout=5)
                return self._json({"ok": True})
            except Exception as e:
                return self._json({"ok": False, "error": str(e)}, status=500)

        if path == "/api/settings":
            body = self._read_json()
            save_settings(body)
            return self._json({"ok": True, "settings": public_settings()})

        if path == "/api/lastfm/connect":
            return self._lastfm_connect()

        if path == "/api/lastfm/complete":
            return self._lastfm_complete()

        if path == "/api/lastfm/disconnect":
            save_settings({"lastfm": {"session_key": "", "username": "", "pending_token": ""}})
            return self._json({"ok": True, "settings": public_settings()})

        if path == "/api/webhook/test":
            body = self._read_json()
            test_urls = body.get("urls") or []
            if not test_urls:
                # Fallback to current settings if no URLs provided in test body
                test_urls = load_settings()["webhook"].get("urls", [])
            
            if not test_urls:
                return self._json({"ok": False, "error": "no urls"}, status=400)
            
            sample_track = {
                "name": "Test Track",
                "artist": "Apple Music Scrobbler",
                "album": "Test Album",
                "duration": 200,
                "position": 100
            }
            payload = json.dumps(build_webhook_payload("play", sample_track)).encode()
            
            results = []
            threads = []
            
            def _test_one(url):
                try:
                    req = urllib.request.Request(url, data=payload, method="POST", headers={"Content-Type": "application/json"})
                    with urllib.request.urlopen(req, timeout=5) as r:
                        results.append({"url": url, "ok": True, "status": r.status})
                except Exception as e:
                    results.append({"url": url, "ok": False, "error": str(e)})

            for url in test_urls:
                if not url.strip(): continue
                t = threading.Thread(target=_test_one, args=(url.strip(),))
                t.start()
                threads.append(t)
            
            for t in threads: t.join()
            
            all_ok = all(r["ok"] for r in results)
            return self._json({"ok": all_ok, "results": results})

        if path == "/api/import":
            return self._import()

        if path == "/api/history/clear":
            db_clear()
            return self._json({"ok": True})

        if path == "/api/app/quit":
            fn = APP_CALLBACKS.get("quit")
            if fn:
                threading.Thread(target=fn, daemon=True).start()
            return self._json({"ok": True})

        if path == "/api/app/open-window":
            fn = APP_CALLBACKS.get("open_window")
            if fn:
                threading.Thread(target=fn, daemon=True).start()
            return self._json({"ok": True})

        if path == "/api/app/open-settings":
            fn = APP_CALLBACKS.get("open_settings")
            if fn:
                threading.Thread(target=fn, daemon=True).start()
            return self._json({"ok": True})

        if path == "/api/app/toggle-notifications":
            s = load_settings().get("notifications", {})
            new_val = not s.get("enabled", True)
            save_settings({"notifications": {"enabled": new_val}})
            return self._json({"ok": True, "enabled": new_val})

        if path == "/api/artwork/reload":
            tracker = TRACKER_REF.get("t")
            if not tracker:
                return self._json({"ok": False, "error": "tracker not running"}, status=500)
            ok = tracker.reload_media()
            return self._json({"ok": ok})

        if path == "/api/edits/upsert":
            b = self._read_json()
            oa = (b.get("original_artist") or "").strip()
            ot = (b.get("original_track") or "").strip()
            if not oa or not ot:
                return self._json({"ok": False, "error": "original_artist/original_track required"}, status=400)
            
            media = b.get("media")
            # ถ้าส่ง itunes_url มาและยังไม่มี animation/masterTall → fetch ให้เสร็จ
            if media and media.get("itunes_url") and not media.get("animation"):
                album_url = media["itunes_url"]
                hi, mt = _fetch_cover_details(album_url)
                if hi: media["artwork"] = hi
                media["masterTall"] = mt
                media["animation"] = _fetch_animated_artwork(album_url)
            
            edits_upsert(oa, ot, b.get("artist", oa), b.get("track", ot), b.get("album", ""), media)
            return self._json({"ok": True})

        if path == "/api/edits/delete":
            b = self._read_json()
            key = b.get("key", "")
            if not key:
                return self._json({"ok": False, "error": "key required"}, status=400)
            return self._json({"ok": edits_delete(key)})

        if path == "/api/edits/clear":
            edits_replace({})
            return self._json({"ok": True})

        self.send_error(404)

    def _lastfm_connect(self):
        s = load_settings()["lastfm"]
        if not (s["api_key"] and s["api_secret"]):
            return self._json({"ok": False, "error": "API key/secret required"}, status=400)
        res = lastfm_call("auth.getToken", {"api_key": s["api_key"]}, s["api_secret"])
        token = res.get("token")
        if not token:
            return self._json({"ok": False, "error": res.get("message", "no token")}, status=500)
        save_settings({"lastfm": {"pending_token": token}})
        auth_url = f"http://www.last.fm/api/auth/?api_key={s['api_key']}&token={token}"
        return self._json({"ok": True, "auth_url": auth_url, "token": token})

    def _lastfm_complete(self):
        s = load_settings()["lastfm"]
        token = s.get("pending_token", "")
        if not token:
            return self._json({"ok": False, "error": "no pending token"}, status=400)
        res = lastfm_call("auth.getSession", {"api_key": s["api_key"], "token": token}, s["api_secret"])
        session = res.get("session") or {}
        sk, name = session.get("key"), session.get("name")
        if not sk:
            return self._json({"ok": False, "error": res.get("message", "auth not approved yet")}, status=400)
        save_settings({"lastfm": {"session_key": sk, "username": name, "pending_token": "", "enabled": True}})
        return self._json({"ok": True, "username": name, "settings": public_settings()})

    def _export(self, fmt):
        events = db_all()
        if fmt == "csv":
            buf = io.StringIO()
            w = csv.writer(buf)
            w.writerow(["timestamp", "event_type", "track_name", "artist_name", "album_name", "duration", "position"])
            for e in events:
                w.writerow([e["timestamp"], e["event_type"], e["track_name"], e["artist_name"], e["album_name"] or "", e["duration"] or 0, e["position"] or 0])
            body = buf.getvalue().encode()
            self.send_response(200)
            self.send_header("Content-Type", "text/csv")
            self.send_header("Content-Disposition", f"attachment; filename=history_{int(time.time())}.csv")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        else:
            body = json.dumps({"version": 1, "events": events}, indent=2).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Disposition", f"attachment; filename=history_{int(time.time())}.json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

    def _import(self):
        length = int(self.headers.get("Content-Length") or 0)
        ctype = self.headers.get("Content-Type", "")
        raw = self.rfile.read(length)

        try:
            if "application/json" in ctype:
                data = json.loads(raw.decode())
                # auto-detect: Music-Scrobbler edit history format
                if is_edit_history_format(data):
                    edits_replace(data)
                    return self._json({"ok": True, "type": "edits", "imported": len(data)})
                events = data.get("events", []) if isinstance(data, dict) else data
            else:
                # CSV → events
                text = raw.decode("utf-8", errors="replace")
                if text.lstrip().startswith("--"):
                    parts = text.split("\r\n\r\n", 1)
                    if len(parts) == 2:
                        text = parts[1].rsplit("\r\n--", 1)[0]
                reader = csv.DictReader(io.StringIO(text))
                events = list(reader)
        except Exception as e:
            return self._json({"ok": False, "error": str(e)}, status=400)

        n = db_bulk_insert(events)
        return self._json({"ok": True, "type": "events", "inserted": n})

    def _read_json(self):
        length = int(self.headers.get("Content-Length") or 0)
        if length == 0:
            return {}
        try:
            return json.loads(self.rfile.read(length).decode())
        except Exception:
            return {}

    def _json(self, obj, status=200):
        body = json.dumps(obj).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, fmt, *args):
        pass


class ReusableServer(socketserver.ThreadingTCPServer):
    allow_reuse_address = True
    daemon_threads = True


if __name__ == "__main__":
    db_init()
    tracker = Tracker()
    TRACKER_REF["t"] = tracker
    t = threading.Thread(target=tracker.run, daemon=True)
    t.start()

    with ReusableServer(("", PORT), Handler) as httpd:
        print(f"♪ Apple Music Scrobbler running at http://localhost:{PORT}")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nStopping...")
            tracker.stop()
